### ISSUE TITLE
USER STORY: Collaboration Request 1

### ISSUE THREAD

**Issue by AtsukoCoffey** [AtsukoCoffey/django-blog#14]
In order to **contact to the site owner** as a **Potential Collaborator**, I can **send a message**

## Acceptance Criteria:

* Acceptance Criteria 1: I can send a message to contact the site owner.
* Acceptance Criteria 2: I can receive the feed back from the action.
* Acceptance Criteria 3:

## Tasks
- [x] Task 1: Create name, email and comment field.
- [x] Task 2: Send form to the data base.
- [x] Task 3: Add message framework to give the feed back to the user.
